
name: BuildTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:      
      - name: Build and Test
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - run: sudo apt-get update && sudo apt-get install -y wayland-protocols
      - run: zig build test
